apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
spec:
  progressDeadlineSeconds: 3
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  strategy:
    canary:
      canaryService: preview-guestbook
      steps:
      - setWeight: 50
      - pause: {}
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/dhpup/guestbook
        name: guestbook
        ports:
        - containerPort: 80
