apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: guestbook-verification-3
  namespace: guestbook
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - sleep 10 && exit 0
                    image: alpine:latest
                    name: test
                restartPolicy: Never