apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
  - stage: prod-uswest
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  subscriptions:
  - git:
      repoURL: https://github.com/dhpup/kargo.git
      branch: main
  - image:
      repoURL: ghcr.io/dhpup/guestbook
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo.git
      writeBranch: stage/test
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/test
    argoCDAppUpdates:
    - appName: guestbook-test
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo.git
      writeBranch: stage/uat
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/uat
    argoCDAppUpdates:
    - appName: guestbook-uat
      appNamespace: argocd
  verification:
    analysisTemplates:
    - name: guestbook-verification
    - name: guestbook-verification-2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-useast
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo.git
      writeBranch: stage/prod-useast
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/prod-useast
    argoCDAppUpdates:
    - appName: guestbook-prod-useast
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-uswest
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/dhpup/kargo.git
      writeBranch: stage/prod-uswest
      kustomize:
        images:
        - image: ghcr.io/dhpup/guestbook
          path: guestbook/stages/prod-uswest
    argoCDAppUpdates:
    - appName: guestbook-prod-uswest
      appNamespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: guestbook-verification-3
  namespace: guestbook
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - exit 1
                    image: alpine:latest
                    name: test
                restartPolicy: Never
