apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: 
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
  - stage: prod-uswest
    autoPromotionEnabled: true