apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: guestbook
  namespace: guestbook
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true
  - stageSelector:
      name: prod-uswest
    autoPromotionEnabled: true