apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-standard
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  vars:
  - name: gitRepo
    value: https://github.com/dhpup/kargo.git
  - name: imageRepo
    value: ghcr.io/dhpup/guestbook
  steps:
  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
        as: out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "Promote ${{ ctx.stage }} to ${{ imageFrom(vars.imageRepo).Tag }}"
  - uses: git-push
    as: push
    config:
      path: ./out
      targetBranch: stage/${{ ctx.stage }}
  - uses: argocd-update
    config:
      apps:
      - name: guestbook-${{ ctx.stage }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-with-pr
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  vars:
  - name: gitRepo
    value: https://github.com/dhpup/kargo.git
  - name: imageRepo
    value: ghcr.io/dhpup/guestbook
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "Promote ${{ ctx.stage }} to ${{ imageFrom(vars.imageRepo).Tag }}"
  - uses: git-push
    as: push
    config:
      path: ./out
      generateTargetBranch: true
  - uses: git-open-pr
    as: openpr
    config:
      repoURL: ${{ vars.gitRepo }}
      sourceBranch: ${{ task.outputs['push'].branch }}
      targetBranch: stage/${{ ctx.stage }}
  - uses: git-wait-for-pr
    as: wait-for-pr
    config:
      repoURL: ${{ vars.gitRepo }}
      prNumber: ${{ task.outputs['openpr'].pr.id }}
  - uses: argocd-update
    config:
      apps:
      - name: guestbook-${{ ctx.stage }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-with-github-action
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  vars:
  - name: gitRepo
    value: https://github.com/dhpup/kargo.git
  - name: imageRepo
    value: ghcr.io/dhpup/guestbook
  - name: githubtoken
    value: githubtoken
  steps:
  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
        as: out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/guestbook/stages/${{ ctx.stage }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: "Promote ${{ ctx.stage }} to ${{ imageFrom(vars.imageRepo).Tag }}"
  - uses: git-push
    as: push
    config:
      path: ./out
      targetBranch: stage/${{ ctx.stage }}
  - uses: gha-dispatch-workflow
    as: dispatch-github-action
    config:
      credentials:
        secretName: ${{ vars.githubtoken }}
      owner: dhpup
      repo: kargo
      workflowFile: example-github-action.yml
      ref: main
      inputs:
        environment: ${{ ctx.stage }}
        version: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: gha-wait-for-workflow
    as: wait-for-github-action
    config:
      credentials:
        secretName: ${{ vars.githubtoken }}
      owner: dhpup
      repo: kargo
      runID: ${{ task.outputs['dispatch-github-action'].runID }}
  - uses: argocd-update
    config:
      apps:
      - name: guestbook-${{ ctx.stage }}
